name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --build-arg JAMULUS_BUILD_VERSION=3_6_0 --file Dockerfile --tag guidowojke/jamulus:3.6.0
